spring.application.name=crud

# PostgreSQL Configuration
# postgresql://root:6SLVsXLfqnEGcNeVdKQHEJsBGxJPBE9w@dpg-d8r2ogegvqtc73ef52v0-a.virginia-postgres.render.com/crud_4jsl
# postgresql://dpg-d8r2ogegvqtc73ef52v0-a/crud_4jsl

spring.datasource.url=jdbc:postgresql://dpg-d8r2ogegvqtc73ef52v0-a/crud_4jsl
spring.datasource.username=root
spring.datasource.password=6SLVsXLfqnEGcNeVdKQHEJsBGxJPBE9w
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
